name: build

# Triggers the workflow on all push or pull request events
on:
  [pull_request, push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Check clang-format
        run: bash .github/workflows/clang-format.sh

      - name: Build on Arduino CLI
        run: bash .github/workflows/build-arduino.sh
